export const SHIFT_CREATE_REQUEST = "SHIFT_CREATE_REQUEST";
export const SHIFT_CREATE_SUCCESS = "SHIFT_CREATE_SUCCESS";
export const SHIFT_CREATE_FAIL = "SHIFT_CREATE_FAIL";
export const SHIFT_CREATE_RESET = "SHIFT_CREATE_RESET";

export const SHIFT_LIST_REQUEST = "SHIFT_LIST_REQUEST";
export const SHIFT_LIST_SUCCESS = "SHIFT_LIST_SUCCESS";
export const SHIFT_LIST_FAIL = "SHIFT_LIST_FAIL";
export const SHIFT_LIST_RESET = "SHIFT_LIST_RESET";

export const SHIFT_LIST_MY_REQUEST = "SHIFT_LIST_MY_REQUEST";
export const SHIFT_LIST_MY_SUCCESS = "SHIFT_LIST_MY_SUCCESS";
export const SHIFT_LIST_MY_FAIL = "SHIFT_LIST_MY_FAIL";
export const SHIFT_LIST_MY_RESET = "SHIFT_LIST_MY_RESET";

export const SHIFT_DETAILS_REQUEST = "SHIFT_DETAILS_REQUEST";
export const SHIFT_DETAILS_SUCCESS = "SHIFT_DETAILS_SUCCESS";
export const SHIFT_DETAILS_FAIL = "SHIFT_DETAILS_FAIL";
export const SHIFT_DETAILS_RESET = "SHIFT_DETAILS_RESET";

export const SHIFT_UPDATE_REQUEST = "SHIFT_UPDATE_REQUEST";
export const SHIFT_UPDATE_SUCCESS = "SHIFT_UPDATE_SUCCESS";
export const SHIFT_UPDATE_FAIL = "SHIFT_UPDATE_FAIL";
export const SHIFT_UPDATE_RESET = "SHIFT_UPDATE_RESET";

export const SHIFT_SWITCH_REQUEST = "SHIFT_SWITCH_REQUEST";
export const SHIFT_SWITCH_SUCCESS = "SHIFT_SWITCH_SUCCESS";
export const SHIFT_SWITCH_FAIL = "SHIFT_SWITCH_FAIL";
export const SHIFT_SWITCH_RESET = "SHIFT_SWITCH_RESET";
